version: 2
updates:
  - package-ecosystem: npm
    directory: /Server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      server-security-updates:
        applies-to: security-updates
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /gortc_main
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
