#pragma once

#define CLOUD_GAMING_VERSION_MAJOR 0
#define CLOUD_GAMING_VERSION_MINOR 1
#define CLOUD_GAMING_VERSION_PATCH 0
#define CLOUD_GAMING_VERSION_BUILD 0
#define CLOUD_GAMING_VERSION "0.1.0"
#define CLOUD_GAMING_VERSION_W L"0.1.0"
